spring:
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password: password
    driverClassName: org.h2.Driver

logging.level.org.springframework.web.filter.CommonsRequestLoggingFilter: DEBUG